### PR TITLE
Updated auto patch firmware

### PR DESCRIPTION
**Pull request by idomp**
updated the firmware.bin.
compiled using vs code + platform.io.

checked on working unit via the OTA updater, all good.

### CODE REVIEW

**Comment by guysoft** [comment]
No source code - can you provide your source code changes as well?
Note that License is GNU General Public License v3.0 which requires this.

**Comment by idomp** [comment]
No source code?
Note that you can go to the merge source and get the code I used to compile this BY LAW.

**Comment by guysoft** [comment]
I dont understand what you said. This PR only changes firmware.bin. Which is a binary that is in the repo.
If you changed something and share a binary, you also need to provide the source changed.

You also just deleted the branch, so I am attaching a screenshot to show only the binary file has been changed. 
Screenshot_20220309_203937

**Comment by idomp** [comment]
I'll help,
this is PR #4.
the one before that was PR #3.

Now, as I didn't want to push both changes in the same PR (as Gil might want to compile by himself - as he did in fact merge #3 and didn't merge #4) you could have found both branches in my fork.

I hope that it make more sense BY LAW OF GNU.


pssst -
next time, you can try to play nice and just ask what's in the PR and not BY THE MIGHTY LAW OF GNU another contributor.

**Comment by guysoft** [comment]
Yes, that is much more helpful.
Now that you mentioned that #3 the the source to #4 I can understand what this PR for.
It does raise the point that perhaps adding CI/CD to the project.

**Comment by guysoft** [comment]
Here you go: #12 I hope that this would help us put this unpleasant exchange behind us and hope it counts by you as playing a little nicer.

**Pull request closed without merging**
